# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  steps:
    - checkout

    # Download and cache dependencies
    - run: echo "$NODE_VERSION" > _NODE_VERSION
    - restore_cache:
        keys:
        - v1-dependencies-node-{{ checksum "_NODE_VERSION" }}-{{ checksum "package-lock.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-node-{{ checksum "_NODE_VERSION" }}-{{ checksum "package-lock.json" }}

    # run tests!
    - run: npm test


version: 2
jobs:
  test8:
    docker:
      - image: circleci/node:8
    environment:
      - NODE_VERSION: "v8"
    <<: *defaults

  test6:
    docker:
      - image: circleci/node:6
    environment:
      - NODE_VERSION: "v6"
    <<: *defaults

  test4:
    docker:
      - image: circleci/node:4
    environment:
      - NODE_VERSION: "v4"
    <<: *defaults

workflows:
  version: 2

  test:
    jobs:
      - test8
      - test6
      - test4